name: reusable-1
run-name: reusable-1-${{ github.run_id }}

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        description: 'Name of the server'
    outputs:
      serverName:
        description: "Name of the server"
        value: ${{ jobs.generate.outputs.serverName }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  context:
    name: Get context
    runs-on: ubuntu-latest
    steps:
      - name: Show default environment variables
        run: |
          echo "job_id: $GITHUB_JOB"
          echo "action_id: $GITHUB_ACTION"
          echo "run_id: $GITHUB_RUN_ID"
          echo "actor: $GITHUB_ACTOR"
          echo "sha: $GITHUB_SHA"
      - name: Show workflow parameter input
        run: |
          echo "name: ${{ github.event.inputs.name }}"
  generate:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      serverName: ${{ steps.step1.outputs.serverName }}
    steps:
      - name: 'Create servername'
        id: step1
        shell: pwsh
        run: |
          $Name = "${{ github.event.inputs.name }}"
          $Number = "01"
          if ($Name) {
              $Output = "$($Name.ToLower())$($Number)-pentest01-dev"
          } else {
              $Output = "sqlsrv$($Number)-pentest01-dev"
          }
          "serverName=$($Output)" >> $env:GITHUB_OUTPUT
