name: status
run-name: status-${{ github.run_id }}

on:
  workflow_dispatch:

jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - name: 'Write summary'
        shell: pwsh
        run: |
          ./pwsh/summary-example.ps1
