name: status
run-name: status-${{ github.run_id }}

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
        type: string
        description: 'github.run_id'

jobs:
  get-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get status using REST API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ inputs.run_id }}/rerun
