name: Windows PowerShell
run-name: windows-powershell_${{ github.run_id }}

on: [workflow_dispatch]

env:
    guid: '00000000-0000-0000-0000-000000000000'

jobs:
    build:
      name: Run Script
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - name: Script
          run: ./pwsh/script-example.ps1
          shell: powershell
